-- Grant Device Permissions to SHOP_OWNER, SHOP_MANAGER, SHOP_STAFF, PARTNER, and other roles
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r, permissions p
WHERE r.name IN ('SHOP_OWNER', 'SHOP_MANAGER', 'SHOP_STAFF', 'PARTNER', 'BRANCH_MANAGER', 'ADMIN', 'PURCHASE_MANAGER', 'SALES_MANAGER')
AND p.name IN (
    'VIEW_DEVICES', 'CREATE_DEVICE', 'UPDATE_DEVICE',
    'VIEW_DEVICE_IMEI', 'VIEW_FULL_DEVICE_IMEI', 'MANAGE_DEVICE_CONDITION',
    'VIEW_DEVICE_INSPECTION', 'CREATE_DEVICE_INSPECTION',
    'UPLOAD_DEVICE_MEDIA', 'VIEW_DEVICE_MEDIA',
    'VIEW_DEVICE_LIFECYCLE', 'BLOCK_DEVICE',
    'VIEW_INVENTORY', 'MANAGE_INVENTORY', 'VIEW_CUSTOMERS', 'CREATE_CUSTOMER', 'UPDATE_CUSTOMER',
    'VIEW_PURCHASES', 'CREATE_PURCHASE', 'VIEW_SALES', 'CREATE_SALE', 'VIEW_SHOPS'
)
ON CONFLICT DO NOTHING;
